kind: Pod
apiVersion: v1
metadata: 
  name: pod-config
spec: 
  containers: 
  - name: nginx
    image: nginx
    envFrom: 
    - configMapRef: 
        name: nginx-config
    # env:
    #  - name: course
    #    valueFrom: 
    #     configMapKeyRef: 
    #       name: nginx-config # name of the config
    #       key: course
    #  - name: duration
    #    valueFrom:
    #     configMapKeyRef: 
    #      name: nginx-config # name of the config
    #      key: duration